version: "3.2"
services:
  nginx:
    image: nginx
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

  secret-api:
    build:
      dockerfile: Dockerfile_api
      context: .
    command: python app.py
    volumes:
      - ./api:/usr/src/app/
      
  public-api:
    build:
      dockerfile: Dockerfile1
      context: .
    command: python app.py
    volumes:
      - ./src:/usr/src/app/
